### ISSUE TITLE
请问大佬为啥我做轮询定时更新闪烁数据

### ISSUE THREAD

**Issue by OTTTTTO** [kobef08/map-canvas#14]
请问大佬为啥我做轮询定时更新闪烁数据，一段时间后整个地图会很卡，闪烁点也会变得很慢；
我每次更新都会clearOverlays删除所有覆盖物；用的是<a href="https://chengquan223.github.io/map-canvas/examples/baidu-map-flashmarker.html" target="_blank">
百度地图-闪烁</a>这个demo

**Comment by GeiDiao** [comment]
不应该删除覆盖物，有个setdata的方法更新数据，而不是删除覆盖物，他的那个删除没有啥用，页面依然存在，只是不停的增加罢了

**Comment by OTTTTTO** [comment]
后面我查看内存数据，你那个里面的Marker数量一直在增加，没办法销毁

**Comment by GeiDiao** [comment]
所以建议你使用 dataset的set方法来更新数据
   https://github.com/huiyan-fe/mapv/blob/v2/src/data/DataSet.md

**Comment by chengquan223** [comment]
> 后面我查看内存数据，你那个里面的Marker数量一直在增加，没办法销毁

你可以查看一下拖拽地图时候调用的函数，里面怎么写的。
```
animationFlag = true;
markers = []; 
```

**Comment by OTTTTTO** [comment]
我每次轮询获取数据的时候会重新new FlashMarker对象并传入新的数据集，并且我也尝试了给markers置空还是会产生很多累计的Marker，但是我console marker数组，这个数组的数量并没有变化
![f1x5m py o mos3bod k s](https://user-images.githubusercontent.com/26369856/50760945-0f570680-1261-11e9-8c30-37e40f6d9b7e.png)
![ztfh j 2 3mqusdxaup 4](https://user-images.githubusercontent.com/26369856/50760946-0f570680-1261-11e9-95da-2c9ff5c30245.png)
由于Marker和百度地图的Marker重名了，所以我改成了mapMarker

**Comment by chengquan223** [comment]
把demo放上来看下吧。

**Comment by OTTTTTO** [comment]
嗯嗯 我明天重新写一个干净一点的demo再贴过来  麻烦大佬了

**Comment by OTTTTTO** [comment]
Demo地址：http://119.23.18.222:8080
![6d5f1d23-7be9-4a8f-a3ae-612e2cef65bb](https://user-images.githubusercontent.com/26369856/50887017-fb600000-142c-11e9-9a34-40bc9e5e25ff.png)
![93d2a5d0-7ad5-44d6-9902-3a6e34b02a14](https://user-images.githubusercontent.com/26369856/50887038-0dda3980-142d-11e9-8c20-946002cef6e0.png)

**Comment by OTTTTTO** [comment]
![9d013fb0-1a5b-4a74-a509-31eac135dea0](https://user-images.githubusercontent.com/26369856/50887357-ef287280-142d-11e9-9a93-b351e8443174.png)
好像就是这里的mapMarker一直没有被释放

**Comment by chengquan223** [comment]
> ![9d013fb0-1a5b-4a74-a509-31eac135dea0](https://user-images.githubusercontent.com/26369856/50887357-ef287280-142d-11e9-9a93-b351e8443174.png)
> 好像就是这里的mapMarker一直没有被释放

看了下，可能是因为没有clearTimeout(id)，你在GetAllWeiXin方法里面加入这句代码试试。
```
if(id){
   clearTimeout(id);
 }
```

**Comment by OTTTTTO** [comment]
可是一旦调用clearTimeout 就会终止我的轮询呀

**Comment by chengquan223** [comment]
> 可是一旦调用clearTimeout 就会终止我的轮询呀

baidu-map-flashMarker.js更新了一下。
`var citys=[{name:"重庆",lnglat:["106.5584","29.569"],color:"#6EE7FF",type:'circle',speed:0.3},{name:"长沙",lnglat:["112.9455","28.2349"],color:"#90EE90",type:'circle',speed:0.6},{name:"贵阳",lnglat:["106.6366","26.6533"],color:"#FF0000",type:'circle',speed:0.8}];`

        var flashMarkerLayer = null;

        setInterval(() => {
            GetAllWeiXin();
        }, 3000);

        function GetAllWeiXin() {
            var num = Math.ceil(Math.random() * citys.length);
            var newArray = getArrItem(citys, num);
            if (flashMarkerLayer) {
                flashMarkerLayer.update(newArray);
            } else {
                flashMarkerLayer = new FlashMarker(map, newArray);
            }
        }
